///////	LOOC BULLSHIT	///////////

#define CHAT_LOOC	1024

#undef TOGGLES_DEFAULT_CHAT	//probably the stupidest thing I have ever done

#define TOGGLES_DEFAULT_CHAT (CHAT_OOC|CHAT_DEAD|CHAT_GHOSTEARS|CHAT_GHOSTSIGHT|CHAT_PRAYER|CHAT_RADIO|CHAT_PULLR|CHAT_GHOSTWHISPER|CHAT_GHOSTPDA|CHAT_GHOSTRADIO|CHAT_LOOC)

//////// END OF LOOC BULLSHIT	///////////////